"""professional expansion phase 1 model updates

Revision ID: b1288e5819b2
Revises: c4f8a1b2d3e5
Create Date: 2026-05-29 12:02:01.336861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1288e5819b2'
down_revision: Union[str, Sequence[str], None] = 'c4f8a1b2d3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create restaurant_status enum type
    restaurant_status = sa.Enum('pending', 'approved', 'suspended', name='restaurant_status')
    restaurant_status.create(op.get_bind())

    # Update orderstatus enum type
    # Use if not exists pattern for safety in case of partial runs
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'out_for_delivery'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'rejected'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('menu_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('prepared_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('dispatched_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    
    # Add status column as nullable first
    op.add_column('restaurants', sa.Column('status', sa.Enum('pending', 'approved', 'suspended', name='restaurant_status'), nullable=True))
    
    # Mark existing restaurants as 'approved'
    op.execute("UPDATE restaurants SET status = 'approved'")
    
    # Make it non-nullable
    op.alter_column('restaurants', 'status', nullable=False)
    
    op.add_column('restaurants', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'deleted_at')
    op.drop_column('restaurants', 'status')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'dispatched_at')
    op.drop_column('orders', 'prepared_at')
    op.drop_column('orders', 'accepted_at')
    op.drop_column('orders', 'rejection_reason')
    op.drop_column('menu_items', 'deleted_at')
    op.drop_column('categories', 'deleted_at')
    # ### end Alembic commands ###

    # Drop restaurant_status enum type
    restaurant_status = sa.Enum('pending', 'approved', 'suspended', name='restaurant_status')
    restaurant_status.drop(op.get_bind())
